title: Timmy Le
logo: /assets/images/profile.png
author:
  name: Timmy Le
  email: timmyle9@gmail.com 
description: >
  Hello, my name is Timmy Le, a recent graduate with a Bachelor of Science Degree in Computer and Electrical Engineer at The Ohio State Univeristy. 

show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
