title: Timmy Le
logo: /assets/images/profile.png
author:
  name: Timmy Le
  email: timmyle9@gmail.com 
description: >
  "Hello, World!" was my first adventure. I hope my journey with you will bring many more! 

show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
