title: Timmy Le
author:
  name: Timmy Le
  email: timmyle9@gmail.com

decription: >
  My name is Timmy Le with a Bachelor of Science Degree in Computer and Electrical Engineer at The Ohio State Univeristy. 

header_pages:
  - Resume.pdf


  
show_downloads: true
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: solarized-dark
