title: Timmy Le
logo: /assets/images/profile.png
author:
  name: Timmy Le
  email: timmyle9@gmail.com 
description: >
  "Hello, World!" Most likely everyone's first coding project. My name is Timmy Le and I hope my first project starts with you!

show_downloads: True
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
