otitle: Timmy Le
author:
  name: Timmy Le
  email: timmyle9@gmail.com

description: >
  Hello, my name is Timmy Le, a recent graduate with a Bachelor of Science Degree in Computer and Electrical Engineer at The Ohio State Univeristy. 

header_pages:
  - resume.md


  
show_downloads: true
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: solarized-dark
