title: Timmy Le
author:
  name: Timmy Le
  email: timmyle9@gmail.com
  
header_pages:
  - resume.md
  
description: >
  Hello, my name is Timmy Le, a recent graduate with a Bachelor of Science Degree in Computer and Electrical Engineer at The Ohio State Univeristy. 

show_downloads: false
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: solarized-dark
